version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis_nfe
    restart: always
    ports:
      - 6379:6379
    volumes:
      - rdpage:/data/ #- ./redis_data:/data/

  app:
    build: .
    container_name: dcifiscal
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links:
      - redis
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis_nfe

volumes:
  rdpage:
    driver: local