version: "3.9"

services:
  app:
    build: .
    container_name: dcifiscal
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app_dcifiscal
      - /usr/app_dcifiscal/node_modules